name: strava-kudos

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          headless: true
          # build: yarn build
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_STRAVA_USERNAME: ${{ secrets.CYPRESS_STRAVA_USERNAME }}
          CYPRESS_STRAVA_PW: ${{ secrets.CYPRESS_STRAVA_PW }}
          CYPRESS_STRAVA_ATHLETE_ID: ${{ secrets.CYPRESS_STRAVA_ATHLETE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: ${{ secrets.CYPRESS_DEBUG }}
